import NavBar from "components/NavBar";
import ProductCard from "components/ProductCard";
import { Button, Heading, SubText, ProductCardContainer, SocialMediaBg, MainPage, PageBreak, PageContainer } from "components/styled";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { SyntheticEvent } from "react";

const Create: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Envited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage>
        <NavBar />
        <PageContainer>
          <Heading>Create your Event</Heading>
          <PageBreak />
          <SubText>Easily host and share events with your friends across any social media.</SubText>
          <PageBreak />
          <Button cta>🎉 Create my next event</Button>
          <PageBreak />
        </PageContainer>
      </MainPage>
    </div>
  );
};

export default Create;
